import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Open_Sans, Inter } from "next/font/google";
import AppProviders from "@/providers";
import "./globals.css";
import { AuthProvider } from "@/providers/auth-provider";
import { createClient } from "@/lib/supabase/server";
import { TooltipProvider } from "@/components/ui/tooltip"


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
});
const openSans = Open_Sans({
    variable: "--font-open-sans",
    subsets: ["latin"],
});
const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});


export const metadata: Metadata = {
    title: "Java Flow",
    description: "Generated by create next app",
};


export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()

    return (
        <html
            lang="en"
            suppressHydrationWarning
        >
            <body
                className={`${geistSans.variable} font-geist antialiased overflow-hidden h-dvh flex flex-col`}
            >
                <AppProviders>
                    <AuthProvider initialUser={user}>
                        <TooltipProvider>
                            {children}
                        </TooltipProvider>
                    </AuthProvider>
                </AppProviders>
            </body>
        </html>
    );
}
